using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dendo.DataContext.Migrations
{
    /// <inheritdoc />
    public partial class AddEvents : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Events"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Title"" text NOT NULL,
                    ""Description"" text,
                    ""StartTime"" timestamp with time zone NOT NULL,
                    ""EndTime"" timestamp with time zone NOT NULL,
                    ""Color"" text NOT NULL,
                    ""UserId"" integer NOT NULL,
                    CONSTRAINT ""PK_Events"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Events_Users_UserId"" FOREIGN KEY (""UserId"")
                        REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_Events_UserId"" ON ""Events"" (""UserId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Events");
        }
    }
}
