using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dendo.DataContext.Migrations
{
    /// <inheritdoc />
    public partial class AddPostsAndComments : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Posts"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""EventId"" integer NOT NULL,
                    ""UserId"" integer NOT NULL,
                    ""Content"" text NOT NULL,
                    ""ImageData"" text,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_Posts"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Posts_Events_EventId"" FOREIGN KEY (""EventId"")
                        REFERENCES ""Events"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_Posts_Users_UserId"" FOREIGN KEY (""UserId"")
                        REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_Posts_EventId"" ON ""Posts"" (""EventId"");
                CREATE INDEX IF NOT EXISTS ""IX_Posts_UserId"" ON ""Posts"" (""UserId"");

                CREATE TABLE IF NOT EXISTS ""Comments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PostId"" integer NOT NULL,
                    ""UserId"" integer NOT NULL,
                    ""Content"" text NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_Comments"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Comments_Posts_PostId"" FOREIGN KEY (""PostId"")
                        REFERENCES ""Posts"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_Comments_Users_UserId"" FOREIGN KEY (""UserId"")
                        REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_Comments_PostId"" ON ""Comments"" (""PostId"");
                CREATE INDEX IF NOT EXISTS ""IX_Comments_UserId"" ON ""Comments"" (""UserId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Comments");

            migrationBuilder.DropTable(
                name: "Posts");
        }
    }
}
